### ISSUE TITLE
Draw Menu Immediately

### ISSUE THREAD

**Issue by dazappa** [davidgiven/wordgrinder#100]
Maybe I'm a bit too picky, but when I press "Escape" to activate the menu, I want it drawn immediately. Currently it is taking a half to a full second to show the menu after Escape is pressed. The same when you press Escape to close the menu. If however, you press another key quickly after pressing Escape, it will immediately redraw. (e.g. Press Escape + Cursor Down in quick succession).

I tried messing about with the source myself, but didn't have much luck.

I tried modifying menu.lua so the MenuClass's activate function used RedrawScreen instead of QueueRedraw, but this did nothing.

I'm not opposed to investigating the source further if you can point me in the right direction, but I'm not a C programmer so results may vary ;)

I doubt the info matters:
I am using latest source code (issue also present in 0.7.2)
Curses version
Linux Mint 20
GNOME Terminal 3.36.1.1

**Comment by davidgiven** [comment]
Sadly, that's not fixable --- it's a consequence of the way terminals work. When curses sees an incoming escape, it can't tell whether it's because the user pressed escape or whether this is just the first byte of a multi-byte key sequence, such as the arrow keys, which all start with escapes. So, it has to wait to see whether more bytes are coming before reporting it to the application. It's configurable but if it's too small a number lots of keys will stop working.

The only proper solution here is to switch to the X11 version, which doesn't have that problem.
