### ISSUE TITLE
Feature Request: estimate page count by # of lines

### ISSUE THREAD

**Issue by bkepps** [davidgiven/wordgrinder#109]
It seems like you could get a more accurate page count if you used the number of lines in a page rather than the number of words in a page. The accuracy would vary depending upon the width of your screen, but with widescreen mode you (the user) could set it so you have about the same width of text as if it were on paper. Is this something that's doable?

**Comment by davidgiven** [comment]
Sorry for the delay...

This would work, but I don't think the results would be useful --- as you say, the number of lines per page would vary depending on the width of the window. I don't want WordGrinder to have to know anything about the physical layout of the text, because that way lies madness. The average count of 250 double spaced lines per pages is actually well established for typewritten manuscripts and is generally enshrined in publisher lore for the standard submission format.

So, thanks for the suggestion, but I'd rather not implement that. If you have any more suggestions, please send them my way! There will be a new release soon...
