### ISSUE TITLE
CTRL-S should save file in last saved format

### ISSUE THREAD

**Issue by jvarsoke** [davidgiven/wordgrinder#16]
If you "Export" a document as a text file, pressing CTRL-S should save to that filename in the chosen format -- not WG format.

[I realize naming the Save-As "Export" is a way to ideologically put a stake in the  ground to say you're sticking with the .wg format, but considering Wordgrinder is the only thing that reads .wg, it would be nice if WG were friendly to people who like to use your UI, but aren't sold on the legacy of the WG format. *been burnt on that before]

**Comment by davidgiven** [comment]
The trouble is that exporting is fundamentally lossy. It's *not* the same as saving, because it discards information. (Quite a lot of information, potentially; it only exports the current subdocument.)

Changing it to export instead, some of the time, potentially runs the risk of massive data loss. So I'm sorry, but that's not an option.

(Bear in mind that you can, if you wish, remap Export->HTML or whatever to ^S. Of course, you can't *save* that setting, because the keymap's one of the things that doesn't get exported...)

**Comment by jvarsoke** [comment]
I think a warning about the loss on the first Export is fair.  If the person agrees, I'd say they know what they are in for.  This is how LibreOffice treats its save-as MS-Doc format.
