### ISSUE TITLE
Feature Request: Option to disable caret flashing

### ISSUE THREAD

**Issue by walulula** [davidgiven/wordgrinder#163]
Hi & thanks for this awesome program.  

I just recently arrived at Wordgrinder after having tried what felt like hundreds of other writing tool on the search for the perfect writing environment for my ADD brain. I really like the simplicity and how it locks out distractions by running in Terminal. 

There's only one thing that i find difficult to work with – the blinking caret. 

Looking at the release page, it looks like it has just recently been implemented. Would it be possible to add an option somewhere to change it back to a static one?

Thanks a lot

**Comment by davidgiven** [comment]
Sorry for the delay, been busy with other things. Yes, this is a reasonable request. Better GUI settings on the list of things to do, at some point; but you mention Terminal, which makes me think you're using the Apple terminal emulator rather than the GUI, and I don't have control of the cursor there. Can you confirm?

**Comment by davidgiven** [comment]
Closing for cleanup.
