### ISSUE TITLE
Request: update *buntu repository with 0.8 (latest available is 0.6)

### ISSUE THREAD

**Issue by JpTiger** [davidgiven/wordgrinder#176]
Hi there, thanks for writing a great piece of software. I've been using it every day for years now. Because I'm using it on a very old machine to turn it into a bit of a typewriter, it not infrequently crashes and needs to be wiped and have everything reinstalled. I put a script together to re-download and recompile, but it seems to have broken somehow (see[ issue here](https://github.com/davidgiven/wordgrinder/issues/175) for details). It would be great if we could just fire up Synaptic or use apt-get to install the latest version, but it seems that the default repositories only go to v0.6, which can't open files created in later versions. Any chance that the repository could be updated to the latest version? Thanks again!

**Comment by davidgiven** [comment]
Sorry for the delay; been focused on other projects...

So the problem here is that I have no control over Ubuntu. I do push out Debian packages, and the most recent there is 0.8, but then Ubuntu picks them up in their own time and they're typically behind. I see that 0.8 is in hirsute, 0.7.2 in focal and 0.7.1 in bionic, but xenial is now in Extended Security Maintenance and only receiving security updates. You'd have to persuade them to backport the new version, or upgrade --- sorry.
