### ISSUE TITLE
ODT Export issue

### ISSUE THREAD

**Issue by nerdythor** [davidgiven/wordgrinder#22]
Hey, I love your word processor. It makes for a great distraction free environment when combined with Ubuntu Server 16.04.

That being said, I've had some issues with ODT Exports via dropbox. It'll state that "something" went wrong and then fail to open in both LibreOffice and Word. I haven't tried the original flavor of OpenOffice yet, but I'm guessing it might be a markup issue. Have you noticed this or is this something new?

**Comment by davidgiven** [comment]
(Sorry for the delay; I 've been away.)

I don't use ODT export much myself, so it's quite plausible that there are bugs. Don't suppose you can provide a minimal example of a WordGrinder file that makes a bogus ODT? (The ODT itself would be useful, too.)

**Comment by davidgiven** [comment]
I've just had a comment on the website that this might be related to having two consecutive spaces in the file --- worth a look.

**Comment by davidgiven** [comment]
I still can't reproduce this.

If you have an example I can look at, could you reopen the bug and attach it, please?

**Comment by ItchyBugReporter** [comment]
I had this issue exactly once a few months ago on 0.7.0. Unfortunately, I don't have the documents any more. If I can reproduce it, I'll attach the documents I used.

The process I followed when it happened went like this (if I remember correctly):
1. Import from .odt
2. Save to .wg
3. Edit the document
4. Save to .wg
5. Export back to .odt, overwriting the original (which was still in place)

**Comment by davidgiven** [comment]
If you can reproduce it, that'd be great. ODT's painful and I'm sure there are unconsidered edge cases.

**Comment by ItchyBugReporter** [comment]
I managed to reproduce it, but GitHub's attachment feature doesn't seem to be working in Chromium or Qupzilla, and I can't get Firefox or Brave working because of some weird "GTK symbols detected and can't both be loaded" issue. Would it be okay if I pushed them to a *temporary* GitHub repo?

**Comment by davidgiven** [comment]
Probably easiest just to email them to me at dg@cowlark.com and I'll attach them here.

**Comment by ItchyBugReporter** [comment]
I emailed the documents. The subject line references this bug. If you want to verify my OpenPGP signature to verify it's from me (since my name & email address don't match my handle here), the fingerprint of the key it should verify with is:

CBB4 4C0B 7794 F668 D486 9B68 02C0 8EE2 7F03 0E92

The -bak file was saved in LibreOffice Writer 6.0.4 then imported into WordGrinder. In the WordGrinder document, you can see I start mashing keys in frustration (I was getting annoyed with WordGrinder for not wanting to reproduce the bug on-demand), and I had to try exporting a bunch of times after that, so I couldn't tell you what I did to make it happen other than repeatedly overwriting the odt file from WordGrinder's export function.

It might be worth looking to see of you can find an ODT library somewhere so you don't have to code it yourself. I know there are a few at http://www.opendocumentformat.org/developers/ (though I don't think any of them are for C or Lua - maybe you could look at the tools at the bottom of the page?).

**Comment by davidgiven** [comment]
Got the attachments --- here they are. I'll have a look; thanks very much!

[Untitled 1-bak.odt.gz](https://github.com/davidgiven/wordgrinder/files/2027345/Untitled.1-bak.odt.gz)
[Untitled 1.odt.gz](https://github.com/davidgiven/wordgrinder/files/2027346/Untitled.1.odt.gz)
[Untitled 1.wg.gz](https://github.com/davidgiven/wordgrinder/files/2027347/Untitled.1.wg.gz)

**Comment by davidgiven** [comment]
Very, very belatedly: I did finally get round to looking at the documents. However, I can't reproduce the problem.

However, I _have_ just fixed a whole pile of bugs in the ODT exporter, so I suspect that whatever it was has been fixed. At least, I hope.

Many apologies for the delay!
