### ISSUE TITLE
Question about design/solution for text drawing

### ISSUE THREAD

**Issue by stianhoiland** [davidgiven/wordgrinder#229]
Hey, I have a project where I need to draw quite a bit of text, and I came across [a discussion you had](https://discourse.libsdl.org/t/renderer-vs-sdl-gpu-for-text-rendering/31977) on the SDL forums about how to get performant text drawing. So I decided to come look at your project and found that you have changed your solution from SDL+SDL_ttf+SDL_fontcache to GLFW+stb_truetype, and I'm simply curious to pick your brain about this decision, and maybe learn something useful for my own project. So, if you'll indulge my question, what made you go this way, and which other options did you consider?

Regards,
Stian

**Comment by davidgiven** [comment]
Hmm. I honestly don't remember at this point. I do know that one of the things which irritated me was that SDL would insist on changing screen mode when going in/out of full screen, causing the entire display to go black for a moment. It was also a pig to make work on Windows and OSX; glfw was much easier in that respect (sdl2-config doesn't return the right set of libraries on Windows).  One thing I originally went with SDL for was because I wanted access to its clipboard functionality, but that turned out to be limited to plain text only, so not useful for me.

**Comment by stianhoiland** [comment]
Ah! Thanks for chiming in :)

**Comment by davidgiven** [comment]
Closing for cleanup.
