### ISSUE TITLE
Bigger font display size needed, option not available in global settings

### ISSUE THREAD

**Issue by PangolinGold** [davidgiven/wordgrinder#257]
Hi, according to the documentation there should be an option under global settings to increase the display font size, but it's not there now. My vision is pretty terrible so I'm struggling. 

Can I can add a line to the config file for this? Documentation gives the X11 command to change font, but again not font size.

For info, the closest option now under Global Setting is "Configure Look and Feel" and it doesn't have options for font or font size.

I'm running Debian unix on a raspberry pi. WordGrinder is amazing!

**Comment by davidgiven** [comment]
The new configuration stuff is in  the dev build only right now (which is what you see when you look at the github page, which is why the documentation doesn't match 0.8).

For 0.8, the font size is set as part of the font name. So doing:

`X11_FONT = "monospace:36"`

...should work (you probably don't want to use 36 point fonts, though!).

**Comment by davidgiven** [comment]
Closing for clenaup.
