### ISSUE TITLE
Better spacing support

### ISSUE THREAD

**Issue by GregTheHun** [davidgiven/wordgrinder#33]
There are two specific areas that I would improve this on. The first being tab support, as a aspiring author I would love for this program to be able to put in a tab when I type that character on the keyboard. Required when you're typing a manuscript that is broken into paragraphs and other such spacing issues. The "indented text, run together" option is not very useful in this regard.

The second issue is that I would like to have the ability to center and left justify text. This is also a very standard thing when you need it for title and other text.

**Comment by davidgiven** [comment]
I'm a bit hesitant to start implementing features like that --- things like first line indent or centering are _formatting_ issues, and WordGrinder deliberately does the absolute bare minimum of formatting, because it's expecting you to export your text, load it into something like OpenOffice or LaTeX, and make it look pretty there.

That said, I'm aware that there are people who prefer to see draft text first-line-indented and with no line to separate paragraphs; that may be doable. But that's a *user interface* issue, and would be a big global switch, and would have no effect at all on the saved documents.

**Comment by davidgiven** [comment]
I've just checked into HEAD the ability to edit things like paragraph spacing and first line indent; so you can change the P style to show indented paragraphs with no line breaks between paragraphs, for the other common viewing style. I'm not _terribly_ convinced about the way the paragraph style editor works, but I believe this is mostly what you want.
