### ISSUE TITLE
Printing via lp as an export option?

### ISSUE THREAD

**Issue by Munchotaur** [davidgiven/wordgrinder#4]
I don't doubt it's tough to write a full print module. But is it possible to configure an export option that sends the file text to lp?

**Comment by davidgiven** [comment]
It'd be straightforward, but I'm not planning to do so --- I don't want functionality which depends on external services because handling dependencies is too hard. (e.g. what happens on Windows?)

This is the kind of job that's best handled by an external script which uses wordgrinder --convert to create a LaTeX file, then runs it through something like pdflatex, and then prints that.
