### ISSUE TITLE
Install on Sierra 

### ISSUE THREAD

**Issue by knightjp** [davidgiven/wordgrinder#42]
Hey, 

How do I install word grinder on Mac OS Sierra.

**Comment by davidgiven** [comment]
I don't know about Sierra, but it builds out of the box on El Capitan. You'll need the version from the git repository, rather than one of the releases. Sorry, there's no installable package for OSX.

Bear in mind that:

- you'll need to build it yourself
- you'll need to have HomeBrew installed

Look in the README for instructions (if the instructions aren't good enough, please let me know).

**Comment by knightjp** [comment]
@davidgiven 
Thanks for the advice. 
I have homebrew installed as well as XQuartz. 
I checked out the read me file.. Sorry, I'm not a developer and it is sort of new to me. 
Could you provide me with a step by step guide?

**Comment by Jachimo** [comment]
In case this helps anyone else... the 0.7.1 release tarball which seemed the most tempting to try first (`wordgrinder-0.7.1-minimal-dependencies-for-debian.tar.xz`) does **not** build on Mac OS X Sierra with Homebrew installed. It throws an error when you run `make` (`No rule to make target `src/c/emu/lua-5.1.5/*.[ch]'). Perhaps this should have been unsurprising but I gave it a whirl anyway.

To build on Mac, you need to install Homebrew (and possibly also Xcode and the command line tools, I'm not sure), either clone the repo or get [the unmarked "Source Code" tarball release](https://github.com/davidgiven/wordgrinder/archive/0.7.1.tar.gz), make sure you have `ninja` installed with Homebrew, and then run `make` and `make install`.

**Comment by davidgiven** [comment]
Yeah, the minimal dependencies version is largely hacked together for Debian and isn't really recommended for anything else.

Thanks for verifying that it works --- always good to know.

**Comment by davidgiven** [comment]
This is now dealt with.
